# -*- coding: utf-8 -*-
"""CSC648_Assignment_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uf8-Kzug3UUVKi7F-DWBzjRzeQtzTlKe
"""

# ============================================================
# CSC648 Assignment #3
# Frozen Lake Variant: MDP Modeling and Policy Optimization
# Author: Tomas Nader
# ID: w10172066
# ============================================================
# This script covers:
# Part 1 - MDP Representation
# Part 2 - Policy Evaluation
# Part 3 - Policy Improvement
# Part 4 - Value Iteration
# Part 5 - Python Implementation
#
# Environment:
# - 4x4 grid with states 0..15
# - Start state = 0
# - Goal state = 15
# - Holes = 5, 7, 12
# - State 11 is SAFE (not terminal)
# - Reward = +1 only when entering state 15, else 0
# - Slippery dynamics:
#       intended direction: 0.4
#       perpendicular dir 1: 0.3
#       perpendicular dir 2: 0.3
# - Discount factor gamma = 0.9
# ============================================================


# =========================
# 1. Basic MDP definition
# =========================

import numpy as np

GRID_SIZE = 4
N_STATES = 16

LEFT = 0
DOWN = 1
RIGHT = 2
UP = 3

ACTIONS = [LEFT, DOWN, RIGHT, UP]

ACTION_NAMES = {
    LEFT: "Left",
    DOWN: "Down",
    RIGHT: "Right",
    UP: "Up"
}

ACTION_SYMBOLS = {
    LEFT: "L",
    DOWN: "D",
    RIGHT: "R",
    UP: "U"
}

START_STATE = 0
GOAL_STATE = 15
HOLES = {5, 7, 12}
TERMINAL_STATES = HOLES | {GOAL_STATE}

GAMMA = 0.9

# Assignment-specific transition behavior:
# chosen action succeeds with probability 0.4
# each perpendicular direction occurs with probability 0.3
ACTION_OUTCOMES = {
    LEFT:  [(0.4, LEFT),  (0.3, UP),    (0.3, DOWN)],
    DOWN:  [(0.4, DOWN),  (0.3, LEFT),  (0.3, RIGHT)],
    RIGHT: [(0.4, RIGHT), (0.3, UP),    (0.3, DOWN)],
    UP:    [(0.4, UP),    (0.3, LEFT),  (0.3, RIGHT)],
}

# ============================================================
# Helper functions for grid movement
# ============================================================

def state_to_rowcol(state):
    """Convert a state number into (row, col)."""
    row = state // GRID_SIZE
    col = state % GRID_SIZE
    return row, col

def rowcol_to_state(row, col):
    """Convert (row, col) into a state number."""
    return row * GRID_SIZE + col

def move(state, action):
    """
    Apply an action in the grid.
    If the move would leave the grid, the agent stays in place.
    """
    row, col = state_to_rowcol(state)

    if action == LEFT:
        new_row, new_col = row, col - 1
    elif action == DOWN:
        new_row, new_col = row + 1, col
    elif action == RIGHT:
        new_row, new_col = row, col + 1
    elif action == UP:
        new_row, new_col = row - 1, col
    else:
        raise ValueError(f"Invalid action: {action}")

    # Boundary rule: if outside the grid, stay in the same state
    if not (0 <= new_row < GRID_SIZE and 0 <= new_col < GRID_SIZE):
        return state

    return rowcol_to_state(new_row, new_col)

def reward_function(state, action, next_state):
    """
    Reward function R(s, a, s'):
    +1 only when entering the goal state.
    0 otherwise.
    """
    return 1.0 if next_state == GOAL_STATE else 0.0

# ============================================================
# Part 1: Build the MDP transition dictionary
# ============================================================

def build_mdp():
    """
    Build transition dictionary P where:
    P[s][a] = list of (prob, next_state, reward, done)

    done = True if next_state is a terminal state
    """
    P = {s: {a: [] for a in ACTIONS} for s in range(N_STATES)}

    for s in range(N_STATES):
        for a in ACTIONS:

            # Terminal states loop to themselves
            if s in TERMINAL_STATES:
                P[s][a] = [(1.0, s, 0.0, True)]
                continue

            transitions = []

            for prob, actual_action in ACTION_OUTCOMES[a]:
                next_state = move(s, actual_action)
                reward = reward_function(s, a, next_state)
                done = next_state in TERMINAL_STATES
                transitions.append((prob, next_state, reward, done))

            P[s][a] = transitions

    return P

P = build_mdp()

# ============================================================
# Print helpers
# ============================================================

def print_transitions_for_state(P, state):
    """Print all transitions for one state."""
    print(f"\nState {state}")
    for a in ACTIONS:
        print(f"  Action {ACTION_NAMES[a]}:")
        for prob, next_state, reward, done in P[state][a]:
            print(f"    prob={prob:.1f}, next={next_state}, reward={reward}, done={done}")

def print_value_grid(V, title="Value Function"):
    """Print a 4x4 grid of state values."""
    print(f"\n{title}")
    for r in range(GRID_SIZE):
        row_vals = []
        for c in range(GRID_SIZE):
            s = rowcol_to_state(r, c)
            row_vals.append(f"{V[s]:7.3f}")
        print(" ".join(row_vals))


def print_policy_grid(policy, title="Policy"):
    """
    Print a 4x4 grid of policy actions.
    H = hole, G = goal
    """
    print(f"\n{title}")
    for r in range(GRID_SIZE):
        row_symbols = []
        for c in range(GRID_SIZE):
            s = rowcol_to_state(r, c)

            if s in HOLES:
                row_symbols.append(" H ")
            elif s == GOAL_STATE:
                row_symbols.append(" G ")
            else:
                row_symbols.append(f" {ACTION_SYMBOLS[policy[s]]} ")
        print(" ".join(row_symbols))

def print_q_values(Q):
    """Print Q(s,a) for each non-terminal state."""
    print("\nQ-values by state")
    for s in range(N_STATES):
        if s in TERMINAL_STATES:
            continue
        print(
            f"State {s:2d}: "
            f"L={Q[s, LEFT]:.4f}  "
            f"D={Q[s, DOWN]:.4f}  "
            f"R={Q[s, RIGHT]:.4f}  "
            f"U={Q[s, UP]:.4f}"
        )


def compare_policies(old_policy, new_policy):
    """Return list of states where the policy action changed."""
    changed_states = []
    for s in old_policy:
        if old_policy[s] != new_policy[s]:
            changed_states.append(s)
    return changed_states

# ============================================================
# Part 2: Policy Evaluation
# ============================================================

def policy_evaluation(policy, P, gamma=0.9, num_iterations=5):
    """
    Perform a fixed number of policy-evaluation iterations.
    Returns:
        V       - value function after num_iterations
        history - list of V after each iteration, including iteration 0
    """
    V = np.zeros(N_STATES)
    history = [V.copy()]

    for _ in range(num_iterations):
        new_V = np.zeros(N_STATES)

        for s in range(N_STATES):
            if s in TERMINAL_STATES:
                continue

            a = policy[s]
            for prob, next_state, reward, done in P[s][a]:
                future = 0.0 if done else gamma * V[next_state]
                new_V[s] += prob * (reward + future)

        V = new_V
        history.append(V.copy())

    return V, history

def policy_evaluation_until_convergence(policy, P, gamma=0.9, theta=0.001):
    """
    Evaluate a fixed policy until convergence.
    Convergence criterion:
        max_s |V_new(s) - V_old(s)| < theta
    """
    V = np.zeros(N_STATES)
    history = [V.copy()]
    iterations = 0

    while True:
        iterations += 1
        delta = 0.0
        new_V = np.zeros(N_STATES)

        for s in range(N_STATES):
            if s in TERMINAL_STATES:
                continue

            a = policy[s]
            for prob, next_state, reward, done in P[s][a]:
                future = 0.0 if done else gamma * V[next_state]
                new_V[s] += prob * (reward + future)

            delta = max(delta, abs(new_V[s] - V[s]))

        V = new_V
        history.append(V.copy())

        if delta < theta:
            break

    return V, history, iterations

# ============================================================
# Part 3: Policy Improvement
# ============================================================

def compute_q_from_v(V, P, gamma=0.9):
    """
    Compute Q(s,a) from a value function V using one-step lookahead.
    """
    Q = np.zeros((N_STATES, len(ACTIONS)))

    for s in range(N_STATES):
        if s in TERMINAL_STATES:
            continue

        for a in ACTIONS:
            for prob, next_state, reward, done in P[s][a]:
                future = 0.0 if done else gamma * V[next_state]
                Q[s, a] += prob * (reward + future)

    return Q

def policy_improvement(V, P, gamma=0.9):
    """
    Improve a policy greedily with respect to V.
    Returns:
        improved_policy
        Q
    """
    Q = compute_q_from_v(V, P, gamma)
    improved_policy = {}

    for s in range(N_STATES):
        if s not in TERMINAL_STATES:
            improved_policy[s] = int(np.argmax(Q[s]))

    return improved_policy, Q

# ============================================================
# Part 4: Value Iteration
# ============================================================

def value_iteration(P, gamma=0.9, theta=0.001):
    """
    Run value iteration until convergence:
        max_s |V_new(s) - V_old(s)| < theta
    Returns:
        V_opt
        optimal_policy
        num_iterations
    """
    V = np.zeros(N_STATES)
    iterations = 0

    while True:
        iterations += 1
        delta = 0.0
        new_V = V.copy()

        for s in range(N_STATES):
            if s in TERMINAL_STATES:
                continue

            action_values = []

            for a in ACTIONS:
                q_sa = 0.0
                for prob, next_state, reward, done in P[s][a]:
                    future = 0.0 if done else gamma * V[next_state]
                    q_sa += prob * (reward + future)
                action_values.append(q_sa)

            new_V[s] = max(action_values)
            delta = max(delta, abs(new_V[s] - V[s]))

        V = new_V

        if delta < theta:
            break

    # Extract optimal policy from converged V
    optimal_policy = {}
    for s in range(N_STATES):
        if s in TERMINAL_STATES:
            continue

        q_values = []
        for a in ACTIONS:
            q_sa = 0.0
            for prob, next_state, reward, done in P[s][a]:
                future = 0.0 if done else gamma * V[next_state]
                q_sa += prob * (reward + future)
            q_values.append(q_sa)

        optimal_policy[s] = int(np.argmax(q_values))

    return V, optimal_policy, iterations


# ============================================================
# Original fixed policy from Figure 1 in the assignment
# ============================================================
# Figure 1 policy arrows:
# 0:R, 1:L, 2:D, 3:U
# 4:L, 6:R
# 8:U, 9:D, 10:U, 11:D
# 13:R, 14:D
#
# Terminal states 5, 7, 12, 15 do not need actions.

original_policy = {
    0: RIGHT,
    1: LEFT,
    2: DOWN,
    3: UP,
    4: LEFT,
    6: RIGHT,
    8: UP,
    9: DOWN,
    10: UP,
    11: DOWN,   # safe state
    13: RIGHT,
    14: DOWN
}

# ============================================================
# MAIN:
# ============================================================

if __name__ == "__main__":

    print("=" * 70)
    print("PART 1: MDP REPRESENTATION")
    print("=" * 70)

    # Print the required example states
    print_transitions_for_state(P, 4)
    print_transitions_for_state(P, 9)
    print_transitions_for_state(P, 14)

    print("\nOriginal policy from the assignment figure:")
    print_policy_grid(original_policy, title="Original Policy (Figure 1)")

    print("\n" + "=" * 70)
    print("PART 2: POLICY EVALUATION (10 ITERATIONS)")
    print("=" * 70)

    V_10, history = policy_evaluation(original_policy, P, gamma=GAMMA, num_iterations=10)

    # Print V after each iteration, including iteration 0
    for i, V in enumerate(history):
        print_value_grid(V, title=f"Value Function after Iteration {i}")

    # Compute final converged value function
    V_conv, history_conv, pe_iterations = policy_evaluation_until_convergence(
        original_policy, P, gamma=GAMMA, theta=0.001
    )

    print_value_grid(V_conv, title="Converged Value Function under Original Policy")
    print(f"\nPolicy evaluation converged in {pe_iterations} iterations.")

    print("\n" + "=" * 70)
    print("PART 3: POLICY IMPROVEMENT")
    print("=" * 70)

    improved_policy, Q = policy_improvement(V_conv, P, gamma=GAMMA)

    print_q_values(Q)
    print_policy_grid(improved_policy, title="Improved Policy")

    changed_states = compare_policies(original_policy, improved_policy)
    print("\nStates where the improved policy differs from the original policy:")
    if changed_states:
        print(changed_states)
        for s in changed_states:
            print(
                f"State {s}: "
                f"{ACTION_NAMES[original_policy[s]]} -> {ACTION_NAMES[improved_policy[s]]}"
            )
    else:
        print("No states changed.")

    print("\n" + "=" * 70)
    print("PART 4: VALUE ITERATION")
    print("=" * 70)

    V_opt, optimal_policy, vi_iterations = value_iteration(P, gamma=GAMMA, theta=0.001)

    print_value_grid(V_opt, title="Optimal Value Function from Value Iteration")
    print_policy_grid(optimal_policy, title="Optimal Policy from Value Iteration")
    print(f"\nValue iteration converged in {vi_iterations} iterations.")

    print("\nComparison: Part 3 improved policy vs Part 4 optimal policy")
    changed_vs_optimal = compare_policies(improved_policy, optimal_policy)
    if changed_vs_optimal:
        print("States that differ:")
        print(changed_vs_optimal)
        for s in changed_vs_optimal:
            print(
                f"State {s}: "
                f"{ACTION_NAMES[improved_policy[s]]} -> {ACTION_NAMES[optimal_policy[s]]}"
            )
    else:
        print("The Part 3 improved policy and the Part 4 optimal policy are the same.")

    print("\n" + "=" * 70)
    print("END OF PROGRAM")
    print("=" * 70)